apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: location-detector
spec:
  annotations:
    seldon.io/istio-gateway: mesh
    seldon.io/istio-host: location-detector
  name: location-detector
  predictors:
    - annotations:
        seldon.io/svc-name: location-detector
      componentSpecs:
        - spec:
            containers:
              - image: 'quay.io/mmurakam/location-detector:v0.2.2'
                name: location-detector
      graph:
        children: []
        endpoint:
          type: REST
        name: location-detector
        type: MODEL
      labels:
        sidecar.istio.io/inject: 'true'
      name: location-detector
      replicas: 1
    - componentSpecs:
        - spec:
            containers:
              - image: 'quay.io/mmurakam/location-detector:v0.2.0'
                name: location-detector-shadow
      graph:
        children: []
        endpoint:
          type: REST
        name: location-detector-shadow
        type: MODEL
      labels:
        sidecar.istio.io/inject: 'true'
      name: location-detector-shadow
      replicas: 1
      shadow: true